# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentcage" do
  version "0.1.0-rc.2"

  on_macos do
    on_intel do
      sha256 "1c9a0fcd4f85b4d716f231abed59117ea1d1d307f450f9f8a53443d40f1fc7e8"
      url "https://github.com/okedeji/agentcage/releases/download/v#{version}/agentcage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec88def93023a2e70b94ad08877f0f5ebe29fa9069ea52449c1f21d5a7e5eee5"
      url "https://github.com/okedeji/agentcage/releases/download/v#{version}/agentcage_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "agentcage"
  desc "Run MCP agents you don't trust, in a cage. Signed and verified by default."
  homepage "https://github.com/okedeji/agentcage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentcage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentcage"]
    end
  end

  # No zap stanza required

end
