# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentcage" do
  version "0.1.0-rc.3"

  on_macos do
    on_intel do
      sha256 "2c50a70d02618ebe283989438fd12cd7a769281993d1c5bab04659158de5c98b"
      url "https://github.com/okedeji/agentcage/releases/download/v#{version}/agentcage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aefb1c4da5b31d5e38b90b87b6be8caa232c72b4c6be976fafdb9f6a09b8e1d4"
      url "https://github.com/okedeji/agentcage/releases/download/v#{version}/agentcage_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "agentcage"
  desc "Run MCP agents you don't trust, in a cage. Signed and verified by default."
  homepage "https://github.com/okedeji/agentcage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentcage"
  bash_completion "completions/agentcage.bash"
  fish_completion "completions/agentcage.fish"
  zsh_completion "completions/agentcage.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentcage"]
    end
  end

  # No zap stanza required

end
