# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpvessel" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "673e3161aa05c0d5f596859049250a0e20799569b3a2a6000b555259998ed28c"
      url "https://github.com/okedeji/mcpvessel/releases/download/v#{version}/mcpvessel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55362fc19c58039815c89aca2588b174bb1be21a6c5ccc0a0897552671e7177c"
      url "https://github.com/okedeji/mcpvessel/releases/download/v#{version}/mcpvessel_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "mcpvessel"
  desc "Build, sign, and run MCP agents in isolated containers"
  homepage "https://github.com/okedeji/mcpvessel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpvessel"
  bash_completion "completions/mcpvessel.bash"
  fish_completion "completions/mcpvessel.fish"
  zsh_completion "completions/mcpvessel.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
