# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpvessel" do
  version "0.1.0-rc.4"

  on_macos do
    on_intel do
      sha256 "a68a80542aeab6a45604baaba47a4c5a5293e3bc8f942106044159364cc55ee6"
      url "https://github.com/okedeji/mcpvessel/releases/download/v#{version}/mcpvessel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3c71a8883d0555109229b6337610acc7cf357d95464528a7b33b42b0426fbbf"
      url "https://github.com/okedeji/mcpvessel/releases/download/v#{version}/mcpvessel_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "mcpvessel"
  desc "Build, sign, and run MCP agents in isolated containers"
  homepage "https://github.com/okedeji/mcpvessel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpvessel"
  bash_completion "completions/mcpvessel.bash"
  fish_completion "completions/mcpvessel.fish"
  zsh_completion "completions/mcpvessel.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpvessel"]
    end
  end

  # No zap stanza required

end
