# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpvessel" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "6ed0bd0bf499a4964a736bc80f52e5ef054b0aff5010cfe26ecde16e76a55927"
      url "https://github.com/okedeji/mcpvessel/releases/download/v#{version}/mcpvessel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce9d965c6ea2e6d6b702f553ebd0639e82c925ada62a405c939f54e12f28a11f"
      url "https://github.com/okedeji/mcpvessel/releases/download/v#{version}/mcpvessel_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "mcpvessel"
  desc "Build, sign, and run MCP agents in isolated containers"
  homepage "https://github.com/okedeji/mcpvessel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpvessel"
  bash_completion "completions/mcpvessel.bash"
  fish_completion "completions/mcpvessel.fish"
  zsh_completion "completions/mcpvessel.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
